// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {engine} from '../models';

export function ApplyEdit(arg1:number):Promise<main.ProgramSnapshot>;

export function ApplyEditSiblings(arg1:number):Promise<main.ProgramSnapshot>;

export function ApplyEditSubtree(arg1:number):Promise<main.ProgramSnapshot>;

export function ApplyEditWithOptions(arg1:number,arg2:boolean):Promise<main.ProgramSnapshot>;

export function GetReconciliationCandidates(arg1:string):Promise<Array<engine.ReconciliationCandidate>>;

export function Greet(arg1:string):Promise<string>;

export function OpenProgram(arg1:string):Promise<main.ProgramSnapshot>;

export function Reconcile(arg1:engine.ReconciliationCandidate):Promise<main.ProgramSnapshot>;

export function ReconcileGroup(arg1:string):Promise<main.ProgramSnapshot>;

export function ReconcileSelected(arg1:Array<string>):Promise<main.ProgramSnapshot>;

export function RemoveEdit(arg1:number):Promise<main.ProgramSnapshot>;

export function RemoveEditSiblings(arg1:number):Promise<main.ProgramSnapshot>;

export function RemoveEditSubtree(arg1:number):Promise<main.ProgramSnapshot>;
